#!/bin/bash

VERSION="2.2.3"
#WEB_URL="http://www.tux.org/~mayer/linux/nbench-byte-2.2.3.tar.gz"
WEB_URL="https://github.com/openthos/oto_lkp/raw/master/benchmark_mirror/jishigou.v0.1.tar.gz"

install()
{
    #make  
cp  -af $BM_NAME  $BM_ROOT
cp -af *.apk $BM_ROOT
cp -af  auto_interact.sh $BM_ROOT   
nc localhost 2600 <<EOF
pm install /data/ubuntu/lkp/benchmark/net.jishigou.t2.8.0.apk
EOF
}
