#!/bin/bash

VERSION="2.2.3"
#WEB_URL="http://www.tux.org/~mayer/linux/nbench-byte-2.2.3.tar.gz"
WEB_URL="https://github.com/openthos/oto_external_lkp/raw/master/benchmark_mirror/launcher.tar.gz"

install()
{
    #make  
cp -af  $BM_NAME  $BM_ROOT
cp -af  auto_interact.sh $BM_ROOT  
cp -af  launcher_benchmark.expt $BM_ROOT   
$LKP_SRC/pack/launcher_pack.expt
}
