#!/bin/bash

VERSION="2.2.3"
#WEB_URL="http://www.tux.org/~mayer/linux/nbench-byte-2.2.3.tar.gz"
WEB_URL="http://192.168.0.180/openthos/oto_test/benchmark_mirror/nbench-byte-2.2.3.tar.gz"

install()
{
    #make
	cp -af $BM_NAME $BM_ROOT
    cp -af *.DAT $BM_ROOT
}
