#!/bin/bash

VERSION="2.2.3"
WEB_URL="https://github.com/openthos/oto_lkp/blob/master/benchmark_mirror/QQ.tar.gz"
#WEB_URL="https://github.com/openthos/oto_lkp/raw/master/benchmark_mirror/QQ.tar.gz"

install()
{
    #make  
cp  -af $BM_NAME  $BM_ROOT
cp -af *.apk $BM_ROOT
cp -af  auto_interact.sh $BM_ROOT  
cp -af  QQ_benchmark.expt $BM_ROOT   
$LKP_SRC/pack/QQ_pack.expt
}
