#!/bin/sh

if vmstat --help | grep -q -F 'timestamp'; then
	opt_timestamp='--timestamp'
else
	opt_timestamp=
fi

#exec vmstat $opt_timestamp -n ${interval:-1} $count
exec vmstat $opt_timestamp -r 0 -d ${interval:-1} $count
