#!/usr/bin/env ruby
while line = STDIN.gets
    case line
    when /test=/
        name = line.sub(/^.*=/,"").chomp
    when /OK/
        puts "#{name}.result: 1"
    when /FAILURES/
        puts "#{name}.result: -1"
    end
end
