#!/usr/bin/env ruby

flag = false

while line = STDIN.gets
	case line.chomp!
	when /^=+LINUX DATA BELOW=+$/
		flag = true
    when /^MEMORY INDEX        : ([0-9\.]+).*$/
        if flag == true
            memindex = $1
            puts 'memindex: ' + memindex
        end
    when /^INTEGER INDEX       : ([0-9\.]+).*$/
        if flag == true
            intindex = $1
            puts 'intindex: ' + intindex
        end
    when /^FLOATING-POINT INDEX: ([0-9\.]+).*$/
        if flag == true
            fltindex = $1
            puts 'fltindex: ' + fltindex
            flag = false
        end
    end
end
